[package]
name = "lesson_3"
version = "0.1.0"
authors = ["Dario Lencina <dario@armore.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
